FROM php:8.1-cli

WORKDIR /app

# Instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Baixar e instalar o Expose
RUN wget https://github.com/beyondcode/expose/raw/master/builds/expose -O /usr/local/bin/expose \
    && chmod +x /usr/local/bin/expose

# Configurar o comando padrão
ENTRYPOINT ["expose"]
